version: '3.1'

services:
  eureka:
    image: mrflick72/eureka-server:latest
    ports:
      - "8761:8761"
    restart: always
    environment:
      - server.port=8761
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - discovery

  configuration-server:
    image: mrflick72/configuration-server:latest
    ports:
      - "8888:8888"
    restart: always
    environment:
      - server.port=8888
      - spring.profiles.active=native,local
      - eureka.instance.preferIpAddress=true
      - spring.cloud.config.server.native.searchLocations=file:///usr/local/configuration-server/config
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    volumes:
      - "${LOCAL_REPO}:/usr/local/configuration-server/config"
    networks:
      - discovery

  onlyone-portal-edgeserver:
    image: mrflick72/onlyone-portal-edgeserver:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      - spring.profiles.active=local
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - discovery

networks:
  discovery:
    driver: bridge