version: '3.1'

services:
  eureka1:
    image: mrflick72/eureka-server:latest
    ports:
      - "8761:8761"
    restart: always
    environment:
      - server.port=8761
      - eureka.instance.hostname=eureka1
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
    networks:
      - discovery
  eureka2:
    image: mrflick72/eureka-server:latest
    ports:
      - "8762:8762"
    restart: always
    environment:
      - server.port=8762
      - eureka.instance.hostname=eureka2
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
    networks:
      - discovery
  eureka3:
    image: mrflick72/eureka-server:latest
    ports:
      - "8763:8763"
    restart: always
    environment:
      - server.port=8763
      - eureka.instance.hostname=eureka3
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
    networks:
      - discovery

  configuration-server:
    image: mrflick72/configuration-server:latest
    ports:
      - "8888:8888"
    restart: always
    environment:
      - server.port=8888
      - spring.profiles.active=native,local
      - eureka.instance.preferIpAddress=true
      - spring.cloud.config.server.native.searchLocations=file:///usr/local/configuration-server/config
      - eureka.client.serviceUrl.defaultZone=http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
    volumes:
      - "${LOCAL_REPO}:/usr/local/configuration-server/config"
    networks:
      - discovery

  onlyone-portal-edgeserver:
    image: mrflick72/onlyone-portal-edgeserver:latest
    restart: always
    environment:
      - spring.profiles.active=local
      - eureka.instance.preferIpAddress=true
      - eureka.client.serviceUrl.defaultZone=http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
    networks:
      - discovery

  envoy:
    image: envoyproxy/envoy:v1.14.1
    restart: always
    ports:
      - 80:80
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - discovery

networks:
  discovery:
    driver: bridge