version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: mvn clean install docker:build -f admin-dashboard/pom.xml
      - run: docker login -u $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
      - run: docker push mrflick72/admin-dashboard:latest