version: '3.1'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9095:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE=true
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_GENERIC_OAUTH_NAME=Vauthenticator
      - GF_AUTH_GENERIC_OAUTH_ENABLED=${AUTH_GENERIC_OAUTH_ENABLED}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${AUTH_GENERIC_OAUTH_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_SCOPES=${AUTH_GENERIC_OAUTH_SCOPES}
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=${AUTH_GENERIC_OAUTH_AUTH_URL}
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=${AUTH_GENERIC_OAUTH_TOKEN_URL}
      - GF_AUTH_GENERIC_OAUTH_API_URL=${AUTH_GENERIC_OAUTH_API_URL}
      - GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_NAME=email
      - GF_AUTH_GENERIC_OAUTH_ALLOWED_DOMAINS=${AUTH_GENERIC_OAUTH_ALLOWED_DOMAINS}
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=${AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP}
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
