version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15671:15671
      - 15672:15672
    networks:
      - messaging

  database:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    networks:
      - database

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "${MONGO_VOLUME}:/var/lib/mongodb"

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - in_memory_storage

networks:
  database:
    driver: bridge
  messaging:
    driver: bridge
  in_memory_storage:
    driver: bridge